# Generated by Django 3.1.4 on 2022-08-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Valor da Renda Mensal')),
            ],
        ),
        migrations.AddField(
            model_name='transacao',
            name='descricao',
            field=models.CharField(default=None, max_length=100, verbose_name='Descrição'),
        ),
    ]
